# Generated by Django 4.0.1 on 2022-01-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='tag',
            field=models.CharField(default='Flutter', max_length=100),
        ),
    ]
