# Generated by Django 4.0.1 on 2022-01-29 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-date_published']},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=models.CharField(max_length=30000),
        ),
    ]
